# Generated by Django 3.2.9 on 2021-12-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profilePicture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDead', models.BooleanField(default=False)),
                ('target', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='frontend.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='frontend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Murder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murderer', to='frontend.player')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='frontend.player')),
            ],
        ),
    ]
