# Generated by Django 3.2.9 on 2021-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_player_isdead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPlayer',
            field=models.BooleanField(default=False),
        ),
    ]
