# Generated by Django 3.2.9 on 2022-01-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211206_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='frontend.user'),
        ),
    ]
