# Generated by Django 3.2.9 on 2021-12-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_user_isplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isPlayer',
        ),
    ]
