# Generated by Django 3.2.9 on 2022-01-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_player_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='isDead',
            new_name='is_dead',
        ),
    ]
